[package]
name = "quirk_echo_enclave_app"
version = "0.1.0"
authors = ["Dzmitry Huba <huba@google.com>"]
edition = "2021"
license = "Apache-2.0"

[workspace]
resolver = "2"
members = ["."]

[dependencies]
quirk_echo_service = { path = "../quirk_echo_service" }
oak_enclave_runtime_support = { path = "../oak_enclave_runtime_support" }
log = "*"
oak_channel = { path = "../oak_channel" }
oak_restricted_kernel_api = { path = "../oak_restricted_kernel_api" }
micro_rpc = { path = "../micro_rpc" }
static_assertions = "*"

[[bin]]
name = "quirk_echo_enclave_app"
test = false
bench = false
