repo = "https://github.com/project-oak/oak"
command = [
  "env",
  "--chdir=quirk_echo_enclave_app",
  "cargo",
  "build",
  "--release"
]
output_path = "./quirk_echo_enclave_app/target/x86_64-unknown-none/release/quirk_echo_enclave_app"
